# mumoco: Multi-Module Conan

image:https://github.com/disroop/mumoco/actions/workflows/build.yml/badge.svg[Build,link=https://github.com/disroop/mumoco/actions/workflows/build.yml]

:uri-sonar: https://sonarcloud.io/dashboard?id=disroop_mumoco
image:https://sonarcloud.io/api/project_badges/measure?project=disroop_mumoco&metric=bugs[Badge,link={uri-sonar}]
image:https://sonarcloud.io/api/project_badges/measure?project=disroop_mumoco&metric=code_smells[Badge,link={uri-sonar}]
image:https://sonarcloud.io/api/project_badges/measure?project=disroop_mumoco&metric=coverage[Badge,link={uri-sonar}]
image:https://sonarcloud.io/api/project_badges/measure?project=disroop_mumoco&metric=duplicated_lines_density[Badge,link={uri-sonar}]
image:https://sonarcloud.io/api/project_badges/measure?project=disroop_mumoco&metric=ncloc[Badge,link={uri-sonar}]
image:https://sonarcloud.io/api/project_badges/measure?project=disroop_mumoco&metric=sqale_rating[Badge,link={uri-sonar}]
image:https://sonarcloud.io/api/project_badges/measure?project=disroop_mumoco&metric=alert_status[Badge,link={uri-sonar}]
image:https://sonarcloud.io/api/project_badges/measure?project=disroop_mumoco&metric=reliability_rating[Badge,link={uri-sonar}]
image:https://sonarcloud.io/api/project_badges/measure?project=disroop_mumoco&metric=security_rating[Badge,link={uri-sonar}]
image:https://sonarcloud.io/api/project_badges/measure?project=disroop_mumoco&metric=sqale_index[Badge,link={uri-sonar}]
image:https://sonarcloud.io/api/project_badges/measure?project=disroop_mumoco&metric=vulnerabilities[Badge,link={uri-sonar}]

image:https://static.deepsource.io/deepsource-badge-light.svg[DeepSource, link=https://deepsource.io/gh/disroop/mumoco?ref=repository-badge]

mumoco or multi-module conan is a tool to help for working with multiple https://conan.io[conan] package simultaneously. mumoco is using pure conan commands and should only simplify the workflow.

mumoco has several features, but the essential feature is that mumoco can find all `conanfile.py` in a given folder and in their sub-folders to create conan packages. Another feature that mumoco has is to execute the conan source command in all found conan packages, this is extremely helpful if you work with conan packages that has external sources.
mumoco also can upload all the conan packages which where created and to login to the remote mumoco has another feature to add and to login to conan remotes.


## Actions

### version

    $ mumoco --version

### help

    $ mumoco --help
    $ mumoco -h

### remotes

mumoco updates all the conan remotes which are defined in mumoco.json file. If the remotes.login parameter in the mumoco.json file is set on a remote then the --user and --password parameter must be set.

    $ mumoco remotes --user john.doe --password 1234567890

### sources

mumoco executes the conan source command with the argument PACKAGE-PATH/tmp, meaning the sources are copied to the PACKAGE-PATH/tmp folder.

### remove

mumoco removes all folders PACKAGE-PATH/tmp. This is helpful to cleanup all sources which mumoco copied with the sources command.

### create

mumoco exports all conan packages into cache and creates all conan packages according to the mumoco.json definition.

### upload



== Code Analysis

image:https://sonarcloud.io/images/project_badges/sonarcloud-black.svg[]


